### ISSUE TITLE
Proper Naming Convention

### ISSUE THREAD

**Issue by KamiNation** [code-collabo/node-mongo#40]
#### Suggested improvement
The files in the doc/staging can be properly named. 

Such as the README.md, Summary.md as this names do not reflect the content of each file and a new README.md should be included.

**Comment by Ifycode** [comment]
Closing this issue for 2 reasons @KamiNation 
1. Conclusions based on the discussion on the docs community channel about the files involved
2. This issue is raised in the wrong repository. All readme and docs related issues are to be sent to the docs repo, whether related to community doc or individual projects.

#
If you feel there is still need to raise this issue, please do so in the issue tab of the [docs repo](https://github.com/code-collabo/docs)
